### ISSUE TITLE
[Feature request] Run plugin command by trigger

### ISSUE THREAD

**Issue by Kristinita** [SublimeText/StatusBarFileSize#3]
### Request

It would be nice, if will be added enable/disable file size by trigger, for example, use command palette or shortcut.

### Justification

I rarely need see my file size. I don't want see file size in sidebar always, because I can not see parts of long status bar messages of other plugins, for example, Sublime Linter.

### Extended behavior

<kbd>Ctrl+Shift+P</kbd> → `StatusBarFileSize: Enable` → I see file size in my status bar. <kbd>Ctrl+Shift+P</kbd> → `StatusBarFileSize: Disable` → I not see file size in my status bar.

Thanks.

**Comment by FichteFoll** [comment]
Just disable and enable the package in that case. It doesn't provide any additional functionality anyway.
