### ISSUE TITLE
Can't deal with unicode characters

### ISSUE THREAD

**Issue by patcunniff-drizly** [SublimeText/StatusBarFileSize#8]
Often, there will be a U+2019 : RIGHT SINGLE QUOTATION MARK in some of my strings and it seems like this plugin dies when it sees any unicode chars. Working on ST3 on mac

**Comment by FichteFoll** [comment]
What are the symptoms of this? Any errors in the console?

**Comment by patcunniff-drizly** [comment]
No console errors. Normally, the bar looks something like this:
~888 Bytes, Line 4, Column 12
but adding a unicode char just removes the size:
Line 4, Column 12
and deleting all unicode chars will make the size show up again

unicode char example (copy/paste into ST):
ᑩ

**Comment by patcunniff-drizly** [comment]
Also just noticed, it's only for non-saved tabs

**Comment by patcunniff-drizly** [comment]
@FichteFoll made a PR ^^ if you want to include it. Encoding is undefined for unsaved files, which maps to ascii instead of utf-8
